name: ling_ling_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  logger: ^2.6.0
  uuid: ^4.5.1
  lottie: ^3.3.1
  get: ^4.7.2
  another_telephony: ^0.4.1
  permission_handler: ^11.0.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.1
  path: ^1.9.0
  sqflite: ^2.4.2
  flutter_defend: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.json
